config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'home#index'

  devise_for :admins, skip: [:registrations]

  resources :projects, only: :index
  get 'projects/contemporary' => 'projects#contemporary', as: 'contemporary_project'
  get 'projects/french_country' => 'projects#french_country', as: 'french_country_project'
  get 'projects/modern_mediterranean' => 'projects#modern_mediterranean', as: 'modern_mediterranean_project'
  get '/projects/nw_traditional' => 'projects#nw_traditional', as: 'nw_traditional_project'
  get '/projects/flat_to_fab' => 'projects#flat_to_fab', as: 'flat_to_fab_project'
  get '/projects/project_exteriors' => 'projects#project_exteriors', as: 'project_exteriors'
  get '/projects/project_interiors' => 'projects#project_interiors', as: 'project_interiors'
  get '/projects/remodel_cbrg' => 'projects#remodel_cbrg', as: 'remodel_cbrg'
  get '/projects/remodel_eb' => 'projects#remodel_eb', as: 'remodel_eb'
  get '/projects/remodel_tig' => 'projects#remodel_tig', as: 'remodel_tig'
  get '/projects/renderings' => 'projects#renderings', as: 'renderings'
  get '/projects/details' => 'projects#details', as: 'details'
  resources :concept_designs, only: :index
  get '/concept_designs/ultra_master_bath' => 'concept_designs#ultra_master_bath', as: 'ultra_master_bath'
  get '/concept_designs/ultra_great_room' => 'concept_designs#ultra_great_room', as: 'ultra_great_room'
  get '/concept_designs/ultra_master_suites' => 'concept_designs#ultra_master_suites', as: 'ultra_master_suites'
  get '/concept_designs/ultra_closet' => 'concept_designs#ultra_closet', as: 'ultra_closet'
  get '/concept_designs/ultra_outdoor_living' => 'concept_designs#ultra_outdoor_living', as: 'ultra_outdoor_living'
  get '/concept_designs/ultra_kitchen' => 'concept_designs#ultra_kitchen', as: 'ultra_kitchen'
  get '/concept_designs/before_and_after' => 'concept_designs#before_and_after', as: 'before_and_after'
  get '/concept_designs/exterior' => 'concept_designs#exterior', as: 'concept_exterior'
  get '/concept_designs/interior' => 'concept_designs#interior', as: 'concept_interior'
  get '/concept_designs/floating_ceiling_panels' => 'concept_designs#floating_ceiling_panels', as: 'floating_ceiling_panels'
  resources :services, only: :index
  get '/process' => 'process#index', as: 'process'
  get '/contact' => 'contact#index', as: 'contact'
  get '/about' => 'about#index', as: 'about'
  get '/interior_design' => 'interior_design#index'
  resources :reviews, only: :index

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController

  def index
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/concept_designs_controller.rb
class ConceptDesignsController < ApplicationController
  def index
  end

  def ultra_master_bath
    render "shared/image_gallery", locals: {
      title: "Ultra Master Bath",
      image_count: 85,
      category: "concepts",
      path: "ultramasterbath"
    }
  end

  def ultra_great_room
    render "shared/image_gallery", locals: {
      title: "Ultra Great Room",
      image_count: 89,
      category: "concepts",
      path: "ultragreatroom"
    }
  end

  def ultra_master_suites
    render "shared/image_gallery", locals: {
      title: "Ultra Master Suites",
      image_count: 88,
      category: "concepts",
      path: "ultramastersuites"
    }
  end

  def ultra_closet
    render "shared/image_gallery", locals: {
      title: "Ultra Closet",
      image_count: 41,
      category: "concepts",
      path: "ultracloset"
    }
  end

  def ultra_outdoor_living
    render "shared/image_gallery", locals: {
      title: "Ultra Outdoor Living",
      image_count: 45,
      category: "concepts",
      path: "ultraoutdoor"
    }
  end

  def ultra_kitchen
    render "shared/image_gallery", locals: {
      title: "Ultra Kitchen",
      image_count: 110,
      category: "concepts",
      path: "ultrakitchen"
    }
  end

  def before_and_after
    render "shared/image_gallery", locals: {
      title: "Before & After",
      image_count: 32,
      category: "concepts",
      path: "conceptbeforeafter"
    }
  end

  def exterior
    render "shared/image_gallery", locals: {
      title: "Exteriors",
      image_count: 48,
      category: "concepts",
      path: "conceptexterior"
    }
  end

  def interior
    render "shared/image_gallery", locals: {
      title: "Interiors",
      image_count: 111,
      category: "concepts",
      path: "conceptinterior"
    }
  end

  def floating_ceiling_panels
  end

end

app/controllers/contact_controller.rb
class ContactController < ApplicationController

  def index
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

app/controllers/interior_design_controller.rb
class InteriorDesignController < ApplicationController

  def index
  end

end

app/controllers/landing_controller.rb
class LandingController < ApplicationController

  def index
    render layout: "landing"
  end

end

app/controllers/process_controller.rb
class ProcessController < ApplicationController

  def index
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
  end

  def contemporary
  end

  def french_country
  end

  def modern_mediterranean
  end

  def nw_traditional
  end

  def flat_to_fab
  end

  def project_exteriors
    render "shared/image_gallery", locals: {
      title: "Project Exteriors",
      image_count: 61,
      category: "projects",
      path: "exteriors"
    }
  end

  def project_interiors
    render "shared/image_gallery", locals: {
      title: "Project Interiors",
      image_count: 94,
      category: "projects",
      path: "interiors"
    }
  end

  def remodel_cbrg
    render "shared/image_gallery", locals: {
      title: "Remodel: Cbrg",
      image_count: 24,
      category: "projects",
      path: "remodelcbrg"
    }
  end

  def remodel_eb
    render "shared/image_gallery", locals: {
      title: "Remodel: E-B",
      image_count: 30,
      category: "projects",
      path: "remodeleb"
    }
  end

  def remodel_tig
    render "shared/image_gallery", locals: {
      title: "Remodel: TIG",
      image_count: 20,
      category: "projects",
      path: "tig"
    }
  end

  def renderings
    render "shared/image_gallery", locals: {
      title: "Renderings",
      image_count: 42,
      category: "projects",
      path: "renderings"
    }
  end

  def details
    render "shared/image_gallery", locals: {
      title: "Details",
      image_count: 51,
      category: "projects",
      path: "details"
    }
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def index
  end

end

app/controllers/services_controller.rb
class ServicesController < ApplicationController

    def index
    end

  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/phrasing_helper.rb
module PhrasingHelper
  def can_edit_phrases?
    admin_signed_in?
  end
end

app/views/concept_designs/before_and_after.html.erb
<!--
<section>
  <div class="container my-5 pb-5">
    <div class="row">
      <div class="col-xl-6 col-lg-7 offset-lg-1">
        <h1 class="font-weight-bold display-3">Before &amp; After</h1>
      </div>
    </div>

    <div class="image-board my-5">
      <% (1..32).each do |index| %>
        <div class="image-board-item">
          <%=
            image_tag "concepts/conceptbeforeafter/small/conceptbeforeafter-#{index}.jpg",
              class: "image-board-img",
              data: { large_src: asset_path("concepts/conceptbeforeafter/large/conceptbeforeafter-#{index}.jpg") }
          %>
        </div>
      <% end %>
    </div>
  </div>
</section>

<%= render partial: "/shared/image_gallery_footer" %>
-->

app/views/concept_designs/index.html.erb
<section class="container my-5 pb-5">
  <div class="row">
    <div class="col-xl-6 col-lg-7 offset-lg-1">
      <h1 class="font-weight-bold display-3">
        Imagine your perfect space.
      </h1>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-6 mx-auto">
      <h2 class="form-heading h3 mt-4 text-center">
        Concepts
      </h2>
      <hr class="accent-line my-4">
    </div>
  </div>
  <div class="text-center my-5">
    <ul class="list-unstyled">
      <li class="h4"><%= link_to "Ultra Master Bath", ultra_master_bath_path %></li>
      <li class="h4"><%= link_to "Ultra Great Room", ultra_great_room_path %></li>
      <li class="h4"><%= link_to "Ultra Master Suites", ultra_master_suites_path %></li>
      <li class="h4"><%= link_to "Ultra Closest", ultra_closet_path %></li>
      <li class="h4"><%= link_to "Ultra Outdoor Living", ultra_outdoor_living_path %></li>
      <li class="h4"><%= link_to "Ultra Kitchen", ultra_kitchen_path %></li>
      <li class="h4"><%= link_to "Before & After", before_and_after_path %></li>
      <li class="h4"><%= link_to "Exterior", concept_exterior_path %></li>
      <li class="h4"><%= link_to "Interior", concept_interior_path %></li>
    </ul>
  </div>
</section>

<%= render partial: "/projects/projects-footer" %>

app/views/home/index.html.slim
section.py-xl-5.py-3.mt-4.position-relative
  .container
    .row
      .col-xl-5.col-lg-6.ml-auto
        h1.display-3.font-weight-bold.mb-5
          | We design spaces you call <span class="home-home">home</span>.
        p.mb-2.home-prop.font-weight-semibold We have one simple goal, to give you a home where family and friends gather, connect, and enjoy one another.
        .clearfix.mt-4
          = link_to contact_path, class: 'btn btn-primary btn-lg basic-shadow d-inline-block align-middle mr-4 font-weight-semibold btn-spacer' do
            | Work with us
            i.ion-ios-home.ml-2
          a.houzz-link.align-middle.d-inline-block href="https://www.houzz.com/pro/jdemarcodesigns/jerome-demarco-artchitecture" rel="noopener" target="_blank"
            = image_tag "featured-on-houzz.jpg", srcset: "#{asset_path('featured-on-houzz@2x.jpg')} 2x", class: "houzz-link-img", height: 33, width: 224, alt: "Featured on Houzz logo", title: "Featured on Houzz"
  .touch-left-img.home-project--featured
    .touch-left-img__bg.smooth-img-wrap
      .smooth-img-placeholder.bg-contemporary data-img-load=(asset_path('contemporary-space.jpg'))
      .smooth-img data-nonfeatured-img=(asset_path('contemporary-space-small.jpg'))
      = link_to contemporary_project_path, class: "project-info" do
        .row
          .col-lg-9.project-info__content
            h4.project-info__title Contemporary Panoramic
            p.project-info__text A mid-century design and clean landscaping work to accent stunning views in this timeless home.
      .home-project-buttons
        a.home-project-button.home-project-prev href="#"
          i.ion-arrow-left-c
        a.home-project-button.home-project-next href="#"
          i.ion-arrow-right-c

section.pt-5
  .container.my-5
    .bg-grid
      .row
        = link_to french_country_project_path, class: "home-project col-md-4 col-sm-6 mt-4 mt-sm-0 mx-auto" do
          .smooth-img-wrap style="padding-bottom: 66.6666%;"
            .smooth-img-placeholder.bg-mediterranean data-img-load=(asset_path('mediterranean-exterior-small.jpg'))
            .smooth-img width="100%" data-featured-img=(asset_path('mediterranean-exterior.jpg')) alt=""
            .project-info
              .project-info__content
                h4.project-info__title French Country
                p.project-info__text An open and collaborative design process helped produce this classic home in Northern California.
        = link_to modern_mediterranean_project_path, class: "home-project col-md-4 col-sm-6 mt-4 mt-sm-0 mx-auto" do
          .smooth-img-wrap style="padding-bottom: 66.6666%;"
            .smooth-img-placeholder.bg-sprawling data-img-load=(asset_path('sprawling-small.jpg'))
            .smooth-img width="100%" data-featured-img=(asset_path('sprawling.jpg')) alt=""
            .project-info
              .project-info__content
                h4.project-info__title Modern Mediterranean
                p.project-info__text Northwest views meet mediterranean inspiration to create this beautiful and peaceful estate.
        = link_to nw_traditional_project_path, class: "home-project col-md-4 col-sm-6 mt-4 mt-md-0 mx-auto" do
          .smooth-img-wrap style="padding-bottom: 66.6666%;"
            .smooth-img-placeholder.bg-traditional data-img-load=(asset_path('transitional-spaces-small.jpg'))
            .smooth-img width="100%" data-featured-img=(asset_path('transitional-spaces.jpg')) alt=""
            .project-info
              .project-info__content
                h4.project-info__title NW Traditional
                p.project-info__text Local materials&mdash;from oversized timbers to natural mossy stone&mdash;helped craft this fabulous transitional home.
      .row.mt-5.py-5.text-center
        .col-lg-8.col-md-10.mx-auto
          .grid-box
            h4.readable-line-height We've served the Northwest with over 20 years of award winning custom-designed homes. Our interior and exterior designed homes engender harmony, and ambient living spaces are uniquely crafted for your family. After all, it's your home.
            hr.accent-line.mt-5

section.py-5.position-relative
  .container
    .row
      .col-xl-7.col-lg-6
        h1.display-4.font-weight-bold Custom Home Design &amp; Home Redesign
    .row.my-4
      .col-xl-7.col-lg-6
        h3.readable-line-height From concept to construction, we're here to turn your dream home into a reality.
    .row
      .col-lg-7.col-lg-6
        .row
          .col-md-6
            p We believe that there is no such thing as a typical customer or a typical home. Each client has unique desires and constraints.
            p In the end, your home, like your family, is like no other.
          .col-md-6
            p.mb-0 Our luxury home designs are innovative. We are driven by inspiration. Artistry and Architecture blend together seamlessly in each home. Details are sublime. Our homes engender harmony, and ambient living spaces are uniquely crafted for your family.
  .col-xl-4.col-lg-5.touch-right-img.home-project--featured.d-none.d-lg-block
    .touch-right-img__bg.smooth-img-wrap
      .smooth-img-placeholder data-img-load=(asset_path "rear-exterior.jpg")
      .smooth-img

hr.accent-line.my-5

= render partial: "collage"
= render partial: "reviews"

javascript:
  lazyLoadImages();
  homeAnimation();
  projectSlideshow();
  reviews();

app/views/projects/contemporary.html.slim
section
  .container.my-5.pb-5
    .row
      .col-xl-6.col-lg-7.offset-lg-1
        h1.font-weight-bold.display-3 Contemporary Panoramic
    .row
      .col-lg-6.mx-auto
        .clearfix.pb-4
          h2.form-heading.h3.mt-4.text-center Northwest
          hr.accent-line.my-4
    .row
      .col-12
        = image_tag "contemporary-space.jpg", width: "100%"
    .my-5.text-center
      .mb-4
        = image_tag "contemporary-space-6.jpg", class: 'align-bottom mr-4', srcset: "#{asset_path('contemporary-space-6@2x.jpg')} 2x"
        = image_tag "contemporary-space-7.jpg", class: 'align-bottom', srcset: "#{asset_path('contemporary-space-7@2x.jpg')} 2x"
      .mb-4
        = image_tag "contemporary-space-2.jpg", class: 'align-middle mr-4', srcset: "#{asset_path('contemporary-space-2@2x.jpg')} 2x"
        = image_tag "contemporary-space-3.jpg", class: 'align-middle', srcset: "#{asset_path('contemporary-space-3@2x.jpg')} 2x"
      .mb-4
        = image_tag "contemporary-space-4.jpg", class: 'align-top mr-4', srcset: "#{asset_path('contemporary-space-4@2x.jpg')} 2x"
        = image_tag "contemporary-space-5.jpg", class: 'align-top', srcset: "#{asset_path('contemporary-space-5@2x.jpg')} 2x"
    .row.mt-5
      .col-md-5.offset-md-1.text-left.mt-5.mb-4
        h3 A mid-century design and clean landscaping work to accent stunning views in this timeless home.
    .row
      .col-xl-7.col-lg-9.mx-auto
        p.h5.readable-line-height.font-weight-normal.my-5 This contemporary home was designed to focus on the awesome view available at its location. Creating a new, updated mid-century vibe produced this bold, timeless design that addresses all of our client's sophisticated modern requirements for an equisite interior and exterior design, as well as producing imaginative solutions for all required necessities for family, friends, and entertaining.
        p.h5.readable-line-height.font-weight-normal.my-5 The home is an elegant, sensitive, exacting, delightful, refined and impeccable flawless gem on the mountain top that surpassed and overwhelmed all of our client's desires and dreams.
    .mt-5.text-center.clearfix
      a.mt-5.mx-auto.p-4.bg-secondary.text-white.h5.d-inline-block.no-underline href="#{french_country_project_path}"
        | Next featured project: French Country
        i.ion-chevron-right.ml-5

= render partial: "projects-footer"

app/views/projects/flat_to_fab.html.slim
section
  .container.my-5.pb-5
    .row
      .col-xl-6.col-lg-7.offset-lg-1
        h1.font-weight-bold.display-3 From Flat to Fab
    .row
      .col-lg-6.mx-auto
        .clearfix.pb-4
          h2.form-heading.h3.mt-4.text-center A full transformation
          hr.accent-line.my-4
    .row
      .col-12
        = image_tag "flat-to-fab-2.jpg", alt: "Home after remodel", width: "100%", srcset: "#{asset_path('flat-to-fab-2@2x.jpg')} 2x"
    .my-5.text-center
      .mb-4
        = image_tag "flat-to-fab-1.jpg", class: 'align-bottom mr-4', srcset: "#{asset_path('flat-to-fab-1@2x.jpg')} 2x"
        = image_tag "flat-to-fab-3.jpg", class: 'align-bottom mr-4', srcset: "#{asset_path('flat-to-fab-3@2x.jpg')} 2x"
        = image_tag "flat-to-fab-4.jpg", class: 'align-bottom', srcset: "#{asset_path('flat-to-fab-4@2x.jpg')} 2x"
      .my-4
        h3
          / i.ion-arrow-up-c.small.mr-3
          em Before & After
          / i.ion-arrow-down-c.small.ml-3
      .mb-4
        = image_tag "flat-to-fab-7.jpg", class: 'align-top mr-4', srcset: "#{asset_path('flat-to-fab-7@2x.jpg')} 2x"
        = image_tag "flat-to-fab-5.jpg", class: 'align-top mr-4', srcset: "#{asset_path('flat-to-fab-5@2x.jpg')} 2x"
        = image_tag "flat-to-fab-6.jpg", class: 'align-top', srcset: "#{asset_path('flat-to-fab-6@2x.jpg')} 2x"
    .row.mt-5
      .col-md-5.offset-md-1.text-left.mt-5.mb-4
        h3 &ldquo;We are extremely happy with the results of our project and couldn't have done it without Jerry.&rdquo;
    .row
      .col-xl-7.col-lg-9.mx-auto
        p.h5.readable-line-height.font-weight-normal.my-5 Our client wanted a simple NW Contemporary without adding more than 50SF to the footprint of the house. We kept the footprint exactly the same as the original except for adding a 6x8’ entry foyer and covered front porch. The exterior remodel included new roofing, sliding, windows, doors, stone work, corbels, and landscaping.
        p.h5.readable-line-height.font-weight-normal.my-5 The client wanted a complete remodel inside and out, but thought the interior spaces just felt too small and confining. The solution was to raise the ceiling and move the front door 8 get to the right. They also wanted a fabulous remodel at a semi-modest price, so we did not change the pitch of the roof or the roofing material. We re-framed the ceiling by removing the webbing in the trusses and marrying 2x12 to the existing rafters. We also installed a beam and posted down to footings below the floor.
        p.h5.readable-line-height.font-weight-normal.my-5 Again, we did not change the pitch of the roof. We did, however, remove walls that made up the original small rooms in order to facilitate an open floor plan. This was a significant factor in the redesign of the kitchen. The outside edges of the “L”-shaped island used to be the location of the walls. We didn’t increase the footprint of the original kitchen, we simply opened it up to the other rooms, which created a very welcoming and large open space. We also ran the same flooring throughout and painted the wall and ceiling the same color. The backsplash is large glass subway tiles with quartz counter tops and painted shaker cabinets.
    .mt-5.text-center.clearfix
      a.mt-5.mx-auto.p-4.bg-secondary.text-white.h5.d-inline-block.no-underline href="#{contemporary_project_path}"
        | Next featured project: Contemporary Panoramic
        i.ion-chevron-right.ml-5

app/views/projects/french_country.html.slim
section
  .container.my-5.pb-5
    .row
      .col-xl-6.col-lg-7.offset-lg-1
        h1.font-weight-bold.display-3 French Countryside
    .row
      .col-lg-6.mx-auto
        .clearfix.pb-4
          h2.form-heading.h3.mt-4.text-center Northern California
          hr.accent-line.my-4
    .row
      .col-12
        = image_tag "mediterranean-exterior.jpg", width: "100%"
    .my-5.text-center
      .mb-4
        = image_tag "french-country-2.jpg", class: 'align-bottom mr-4', srcset: "#{asset_path('french-country-2@2x.jpg')} 2x"
        = image_tag "french-country-3.jpg", class: 'align-bottom', srcset: "#{asset_path('french-country-3@2x.jpg')} 2x"
      .mb-4
        = image_tag "french-country-4.jpg", class: 'align-middle mr-4', srcset: "#{asset_path('french-country-4@2x.jpg')} 2x"
        = image_tag "french-country-5.jpg", class: 'align-middle', srcset: "#{asset_path('french-country-5@2x.jpg')} 2x"
      .mb-4
        = image_tag "french-country-6.jpg", class: 'align-middle mr-4', srcset: "#{asset_path('french-country-6@2x.jpg')} 2x"
        = image_tag "french-country-7.jpg", class: 'align-middle', srcset: "#{asset_path('french-country-7@2x.jpg')} 2x"
      .mb-4
        = image_tag "french-country-8.jpg", class: 'align-top mr-4', srcset: "#{asset_path('french-country-8@2x.jpg')} 2x"
    .row.mt-5
      .col-md-5.offset-md-1.text-left.mt-5.mb-4
        h3 An open and collaborative design process helped produce this classic home in Northern California.
    .row
      .col-xl-7.col-lg-9.mx-auto
        p.h5.readable-line-height.font-weight-normal.my-5 &ldquo;My wife and I planned to build a new home for several years and sought out Jerry DeMarco as a designer. Jerry showed us examples of his work, including a style that we really liked.
        p.h5.readable-line-height.font-weight-normal.my-5 &ldquo;We were at first concerned about the distance between us, Jerry being located in Oregon and my wife and I located in Northern California, but that concern turned out to be a non-issue. Nearly all of our communication was done via telephone and by emailing plans and sepcifications between us and his studio. Most evenings during the design process my wife and I would review new design ideas and/or changes to previous drawings and call Jerry to discuss them and new design ideas he wanted us to consider. Very soon after our on-line and telephone meetings we would have new drawing via email to review. Jerry visited our site a couple of times to get a feel for it, but the rest of the process was accomplished via those two modes.
        p.h5.readable-line-height.font-weight-normal.my-5 &ldquo;We had some pretty specific ideas about our floor plan and the exterior look of the new home. Jerry helped us through the design and build process. When the plans were finished, Jerry emailed them to a local print shop who printed them for building permits and construction drawings. He also worked with our contractor with design questions during the construction phase.
        p.h5.readable-line-height.font-weight-normal.my-5 &ldquo;My wife and I had a great time working with Jerry to create the beautiful design and building of our new home. Any new custom home design for us will definitely have Jerry's name in the margin.&rdquo;
    .mt-5.text-center.clearfix
      a.mt-5.mx-auto.p-4.bg-secondary.text-white.h5.d-inline-block.no-underline href="#{modern_mediterranean_project_path}"
        | Next featured project: Modern Mediterranean
        i.ion-chevron-right.ml-5

= render partial: "projects-footer"

app/views/projects/index.html.slim
section
  .container.my-5.pb-5
    .row
      .col-xl-6.col-lg-7.offset-lg-1
        h1.font-weight-bold.display-3 Dream homes come true.
    .row
      .col-lg-6.mx-auto
        .clearfix.pb-4
          h2.form-heading.h3.mt-4.text-center Featured projects
          hr.accent-line.my-4
    .row.mt-5.mb-5.pb-5
      .col-lg-7.col-md-10.mx-auto
        = link_to contemporary_project_path do
          .smooth-img-wrap style="padding-bottom: 66.6666%;"
            .smooth-img-placeholder data-img-load=(asset_path('contemporary-space.jpg'))
            img.smooth-img width="100%"
            .project-info
              h3 Contemporary Panoramic
    .row.mb-5.pb-5
      .col-lg-7.col-md-10.ml-auto
        = link_to french_country_project_path do
          .smooth-img-wrap style="padding-bottom: 66.6666%;"
            .smooth-img-placeholder data-img-load=(asset_path('mediterranean-exterior.jpg'))
            img.smooth-img width="100%"
            .project-info
              h3 French Country
    .row.mb-5.pb-5
      .col-lg-7.col-md-10
        = link_to modern_mediterranean_project_path do
          .smooth-img-wrap style="padding-bottom: 66.6666%;"
            .smooth-img-placeholder data-img-load=(asset_path('sprawling.jpg'))
            img.smooth-img width="100%"
            .project-info
              h3 Modern Mediterranean
    .row.mb-5
      .col-lg-7.col-md-10.ml-auto
        = link_to nw_traditional_project_path do
          .smooth-img-wrap style="padding-bottom: 66.6666%;"
            .smooth-img-placeholder data-img-load=(asset_path('transitional-spaces.jpg'))
            img.smooth-img width="100%"
            .project-info
              h3 Northwest Traditional
    .row.mb-5.pb-5
      .col-lg-7.col-md-10
        = link_to flat_to_fab_project_path do
          .smooth-img-wrap style="padding-bottom: 66.6666%;"
            .smooth-img-placeholder data-img-load=(asset_path('flat-to-fab-2.jpg'))
            img.smooth-img width="100%"
            .project-info
              h3 From Flat to Fab
    .row
      .col-lg-6.mx-auto
        .clearfix.pb-4
          h2.form-heading.h3.mt-4.text-center Our Other Work
          hr.accent-line.my-4
    .text-center
      ul.list-unstyled
        li.h4 = link_to "Project Exteriors", project_exteriors_path
        li.h4 = link_to "Project Interiors", project_interiors_path
        li.h4 = link_to "Remodel: Cbrg", remodel_cbrg_path
        li.h4 = link_to "Remodel: E-B", remodel_eb_path
        li.h4 = link_to "Remodel: Tig", remodel_tig_path
        li.h4 = link_to "Renderings", renderings_path
        li.h4 = link_to "Details", details_path

= render partial: "projects-footer"

javascript:
  lazyLoadImages();